### ISSUE TITLE
Cannot find/open tsne_multicore shared library

### ISSUE THREAD

**Issue by SumNeuron** [DmitryUlyanov/Multicore-TSNE#32]
I installed this.
It works inside the directory. 
When I move it too dist-packages, it breaks. 
It is on sys.path

**Comment by guenteru** [comment]
I just tried to replicate this and it works fine for me (python 3.6.2).
Which python version are you running?

**Comment by SumNeuron** [comment]
3.6

**Comment by guenteru** [comment]
which command did you use to install?

**Comment by SumNeuron** [comment]
```
git clone https://github.com/DmitryUlyanov/Multicore-TSNE.git
cd Multicore-TSNE/
pip install --no-cache-dir .
```

**Comment by guenteru** [comment]
try without `--no-cache-dir`

**Comment by SumNeuron** [comment]
I did, then it fails

**Comment by AndrewCurran** [comment]
I am having the same problem on 3.6.2.

**Comment by heurainbow** [comment]
same problem

**Comment by overdrivek** [comment]
any updates regarding this? i have the same issue.

**Comment by DmitryUlyanov** [comment]
Please try to install with `python setup.py install`

**Comment by akupemula** [comment]
I solved the problem by compiling the shared .so file manually using g++

**Comment by mpenagar** [comment]
I got the same problem with python 3.4 when running the example inside the installation directory "Multicore-TSNE"

Worked if I run python outside the installation directory.

**Comment by LukasMosser** [comment]
Python 2.7
Compiled using windows build tools 2017
Installed via pip install. and python setup.py install
Neither work.
Any idea why?

**Comment by arianhosseini** [comment]
I had the same problem. This is how I fixed it:
* go to the parent directory 
* run `pip install Multicore-TSNE/`
then the egg is added to `/usr/local/lib/python2.7/dist-packages/`. Same can be done on python3.x with pip3.

**Comment by darthdeus** [comment]
Tried both `python setup.py install`, running `pip install .` and running `pip install Multicore-TSNE` from the parent dir, neither works on Windows 10 with 2017 devtools.

**Comment by abrahamnunes** [comment]
I was experiencing this on one of my machines and so I just updated numpy in my Anaconda distribution. That seemed to fix it.

**Comment by jroakes** [comment]
The problem here is that the file tsne_multicore.dll has been compiled with i386 architecture (32-bit) so it will not work on 64-bit systems, thus the "error 0xc1".  There is no workaround for Windows other than installing the 32-bit version of Python.  Would really like to test this, so hopefully the developer can post a 64-bit version to switch out the problematic DLL.

**Comment by haltuf** [comment]
I have same problem on Win 10, tried to install using all methods mentioned.

**Comment by RichardMeyes** [comment]
@jroakes THX! That worked perfectly!

**Comment by fingoldo** [comment]
@DmitryUlyanov could you kindly take a look, there is still a problem on Windows...

**Comment by adrisede** [comment]
Hi, I also have the same problem on Win 10, and also tried with all the methods mentioned and couldn't make it to work.

**Comment by RebekkaWegmann** [comment]
I also have the same issue on Win 10.

**Comment by IrisStark** [comment]
Same issue on Win 10. Tried everything above.

**Comment by rajbhatti** [comment]
Did any one find any solution? I am getting the same error

**Comment by worm6206** [comment]
If you are on Windows, 
1. Install MinGW 64. I had it already, but you can install from http://mingw-w64.org/doku.php. 
2. Then add MinGW flag as https://github.com/DmitryUlyanov/Multicore-TSNE/issues/32#issuecomment-383385516 describes. 
3. Next, build with `python setup.py install` 
4. and install with `pip install .`

**Comment by bscully27** [comment]
I spent an hour trying different installs with cmd, mingw, pip, setup.py.  I'm using python 2.7.10 on windows7.  Nothing worked.

I then tried on python3.6, worked immediately.

**Comment by mosynaq** [comment]
I build the lib using MSVS 2017 and it worked. I can share the file. But there is an easier way: use pypi wheel package (pip regular installation process) ! It simply works!

**Comment by eardic** [comment]
I added  '-DCMAKE_GENERATOR_PLATFORM=x64' flag and the problem solved in Win64 (Win10) 

if 0 != execute(['cmake',
                         '-DCMAKE_GENERATOR_PLATFORM=x64', <----- THIS
                         '-DCMAKE_BUILD_TYPE={}'.format(build_type),
                         '-DCMAKE_VERBOSE_MAKEFILE={}'.format(int(self.verbose)),

**Comment by ZippoML** [comment]
> I added '-DCMAKE_GENERATOR_PLATFORM=x64' flag to the setup.py and the problem solved in Win64 (Win10) and Python 3.5.4.
> 
> if 0 != execute(['cmake',
> '-DCMAKE_GENERATOR_PLATFORM=x64', <----- THIS
> '-DCMAKE_BUILD_TYPE={}'.format(build_type),
> '-DCMAKE_VERBOSE_MAKEFILE={}'.format(int(self.verbose)),

thx, solved my problem. win 10

**Comment by Po-Shin** [comment]
Hi, I used pip install MulticoreTSNE and got the same error while running my code. Anyone got the solution to fix it?

thanks!

**Comment by ghayth82** [comment]
> > I added '-DCMAKE_GENERATOR_PLATFORM=x64' flag to the setup.py and the problem solved in Win64 (Win10) and Python 3.5.4.
> > if 0 != execute(['cmake',
> > '-DCMAKE_GENERATOR_PLATFORM=x64', <----- THIS
> > '-DCMAKE_BUILD_TYPE={}'.format(build_type),
> > '-DCMAKE_VERBOSE_MAKEFILE={}'.format(int(self.verbose)),
> 
> thx, solved my problem. win 10

where I can find the setup.py file, please?

**Comment by ghayth82** [comment]
> If you are on Windows,
> 
> 1. Install MinGW 64. I had it already, but you can install from http://mingw-w64.org/doku.php.
> 2. Then add MinGW flag as [#32 (comment)](https://github.com/DmitryUlyanov/Multicore-TSNE/issues/32#issuecomment-383385516) describes.
> 3. Next, build with `python setup.py install`
> 4. and install with `pip install .`

hi
can you help me , what do you mean by "build with `python setup.py install" then  install with `pip install .` ?
can you provide me with full commands please

**Comment by ZippoML** [comment]
I alrdy forgot what i did to solve the problem. But i think the steps are:
1. download package from here https://github.com/DmitryUlyanov/Multicore-TSNE
2. open setup.py install with notepad or jupyter
3. change the code as was written above
4. install the pakage by command in cmd. python setup.py install

**Comment by ZippoML** [comment]
> > If you are on Windows,
> > 
> > 1. Install MinGW 64. I had it already, but you can install from http://mingw-w64.org/doku.php.
> > 2. Then add MinGW flag as [#32 (comment)](https://github.com/DmitryUlyanov/Multicore-TSNE/issues/32#issuecomment-383385516) describes.
> > 3. Next, build with `python setup.py install`
> > 4. and install with `pip install .`
> 
> hi
> can you help me , what do you mean by "build with `python setup.py install" then install with `pip install .` ?
> can you provide me with full commands please

I alrdy forgot what i did to solve the problem. But i think the steps are:

1. download package from here https://github.com/DmitryUlyanov/Multicore-TSNE
2. open setup.py install with notepad or jupyter
3. change the code as was written above
4. install the pakage by command in cmd. python setup.py install

**Comment by arikanev** [comment]
Also having this issue on OSX, @akupemula, can you expand on how to compile the .so with g++ manually? Thanks!

**Comment by Yerne** [comment]
i've done everything mentioned here https://github.com/DmitryUlyanov/Multicore-TSNE/issues/32#issuecomment-464067679 
compiled withcmake x64 and mingw-w64\x86_64-8.1.0-posix-sjlj-rt_v6-rev0

but still getting 
"RuntimeError: Cannot find/open tsne_multicore shared library"

**Comment by bscully27** [comment]
I used to have a working multicoreTSNE on python3.6 in windows7 but
uninstalled then tried re-installing, same problem "RuntimeError: Cannot
find/open tsne_multicore shared library".

tried both pip and clone installs.

**Comment by Yerne** [comment]
something here need to be fixed, i dont know what exactly:

       path = os.path.dirname(os.path.realpath(__file__))
        try:
            sofile = (glob(os.path.join(path, 'libtsne*.so')) +
                      glob(os.path.join(path, '*tsne*.dll')))[0]
            self.C = self.ffi.dlopen(os.path.join(path, sofile))

**Comment by Yerne** [comment]
> 
> 
> I added '-DCMAKE_GENERATOR_PLATFORM=x64' flag to the setup.py and the problem solved in Win64 (Win10) and Python 3.5.4.
> 
> if 0 != execute(['cmake',
> '-DCMAKE_GENERATOR_PLATFORM=x64', <----- THIS
> '-DCMAKE_BUILD_TYPE={}'.format(build_type),
> '-DCMAKE_VERBOSE_MAKEFILE={}'.format(int(self.verbose)),

this helped me on win 10 x64 python 3.6.8

**Comment by Applenice** [comment]
> I added '-DCMAKE_GENERATOR_PLATFORM=x64' flag to the setup.py and the problem solved in Win64 (Win10) and Python 3.5.4.
> 
> if 0 != execute(['cmake',
> '-DCMAKE_GENERATOR_PLATFORM=x64', <----- THIS
> '-DCMAKE_BUILD_TYPE={}'.format(build_type),
> '-DCMAKE_VERBOSE_MAKEFILE={}'.format(int(self.verbose)),

Thank you very much, this solved my problem，this helped me on windows 10 x64  python 3.6.5

**Comment by mukesh5** [comment]
> I added '-DCMAKE_GENERATOR_PLATFORM=x64' flag to the setup.py and the problem solved in Win64 (Win10) and Python 3.5.4.
> 
> if 0 != execute(['cmake',
> '-DCMAKE_GENERATOR_PLATFORM=x64', <----- THIS
> '-DCMAKE_BUILD_TYPE={}'.format(build_type),
> '-DCMAKE_VERBOSE_MAKEFILE={}'.format(int(self.verbose)),

Thanx this solved my problem on win10 & python 3.5.4

**Comment by jonimatix** [comment]
> > I added '-DCMAKE_GENERATOR_PLATFORM=x64' flag to the setup.py and the problem solved in Win64 (Win10) and Python 3.5.4.
> > if 0 != execute(['cmake',
> > '-DCMAKE_GENERATOR_PLATFORM=x64', <----- THIS
> > '-DCMAKE_BUILD_TYPE={}'.format(build_type),
> > '-DCMAKE_VERBOSE_MAKEFILE={}'.format(int(self.verbose)),
> 
> Thanx this solved my problem on win10 & python 3.5.4

This works for me as well. If you had already installed the package, just type pip uninstall MulticoreTSNE and then reinstall it..

**Comment by micro0524** [comment]
The above solution works for me. Let me summarize the solution:

1. If you installed package before, `pip uninstall MulticoreTSNE`
2. Clone the source `git clone https://github.com/DmitryUlyanov/Multicore-TSNE.git`
3. Edit `/Multicore-TSNE/setup.py`, 

Find these piece of code and add one line
```
if 0 != execute(['cmake',
'-DCMAKE_GENERATOR_PLATFORM=x64', <----- THIS
'-DCMAKE_BUILD_TYPE={}'.format(build_type),
'-DCMAKE_VERBOSE_MAKEFILE={}'.format(int(self.verbose)),
```

4. install by source
```
cd /Multicore-TSNE
pip install .
```

**Comment by xDarkLemon** [comment]
Does anyone know hot to fix it on Mac OS?

**Comment by zfhxi** [comment]
## Problem：

demo：

```python
from sklearn.datasets import load_digits
from MulticoreTSNE import MulticoreTSNE as TSNE
from matplotlib import pyplot as plt

digits = load_digits()
embeddings = TSNE(n_jobs=4).fit_transform(digits.data)
vis_x = embeddings[:, 0]
vis_y = embeddings[:, 1]
plt.scatter(vis_x, vis_y, c=digits.target, cmap=plt.cm.get_cmap("jet", 10), marker='.')
plt.colorbar(ticks=range(10))
plt.clim(-0.5, 9.5)
plt.show()
```

If you run this demo, the error will occurre：

```python
Traceback (most recent call last):
  File "/xxxx/miniconda3/xxx/test_MultiCore_TSNE.py", line 10, in <module>
    embeddings = TSNE(n_jobs=4).fit_transform(digits.data)
  File "/xxxx/miniconda3/xxx/site-packages/MulticoreTSNE/__init__.py", line 103, in __init__
    raise RuntimeError('Cannot find/open tsne_multicore shared library')
RuntimeError: Cannot find/open tsne_multicore shared library
```

## Explore：

Open `/xxx//miniconda3/xxx/site-packages/MulticoreTSNE/__init__.py` to check what makes it happen，and locate to around line 103：

```python
path = os.path.dirname(os.path.realpath(__file__))
try:
    sofile = (glob(os.path.join(path, "libtsne*.so")) + glob(os.path.join(path, "*tsne*.dll")))[0]
    self.C = self.ffi.dlopen(os.path.join(path, sofile))
except (IndexError, OSError):
    raise RuntimeError('Cannot find/open tsne_multicore shared library')
```

To get more concrete information about this error, we can modified this source code as follow：

```python
path = os.path.dirname(os.path.realpath(__file__))
try:
    sofile = (glob(os.path.join(path, "libtsne*.so")) + glob(os.path.join(path, "*tsne*.dll")))[0]
    self.C = self.ffi.dlopen(os.path.join(path, sofile))
# except (IndexError, OSError):
# raise RuntimeError('Cannot find/open tsne_multicore shared library')

except IndexError as e:
    print(e)
    exit(-1)

except OSError as e1:
    print(e1)
    exit(-1)
```

Then run the demo again, errors may occurr as follow：

```python
cannot load library '/xxxx/miniconda3/xxx/site-packages/MulticoreTSNE/libtsne_multicore.so':
 /xxxx/miniconda3/xxx/site-packages/scipy/_lib/_uarray/../../../../../libstdc++.so.6: version `GLIBCXX_3.4.29' not found
 (required by /xxxx/miniconda3/xxx/site-packages/MulticoreTSNE/libtsne_multicore.so)
```

From this information, we can see that there's no `GLIBCXX_3.4.29` in ``libstdc++.so.6`. Test it as follow:

```python
$ real path /xxxxx/miniconda3/xxx/scipy/_lib/_uarray/../../../../../libstdc++.so.6
$ /xxxx/miniconda3/xxx/lib/libstdc++.so.6.0.26
$ strings /xxxx/miniconda3/xxx/lib/libstdc++.so.6.0.26  | grep GLIBCXX_3.4.2
$ # return nothing
```

## Solution

Reference：[https://blog.csdn.net/qq_39295044/article/details/86685729](https://blog.csdn.net/qq_39295044/article/details/86685729)

We can find `/usr/lib/libstdc++.so.6.0.29` contains `GLIBCXX_3.4.29`, test it:

```python
$ strings /usr/lib/libstdc++.so.6 | grep GLIBCXX_3.4.29
GLIBCXX_3.4.29
GLIBCXX_3.4.29
```

This lib file satisfies the requirement, so we can replace `/xxxx/miniconda3/xxx/lib/libstdc++.so.6.0.26` with `/usr/lib/libstdc++.so.6.0.29`:

```python
$ mv /xxxx/miniconda3/xxx/lib/libstdc++.so.6.0.26 /xxxx/miniconda3/xxx/lib/libstdc++.so.6.0.26_bak
$ ln -s /usr/lib/libstdc++.so.6.0.29 /xxxx/miniconda3/xxx/lib/libstdc++.so.6.0.26
```

Run the demo again, good lucky!

**Comment by shayantabatabaee** [comment]
I also encountered a similar issue, but I managed to resolve it by following these steps:

1. First, I downloaded the Mingw64 compiler for Windows from the official website: https://winlibs.com/#download-release.

2. Once the download was complete, I installed the Mingw64 compiler on my system.

3. After installing Mingw-w64, I changed the following code to build the project:


```
if 0 != execute(['cmake',  
                         '-G', 'MinGW Makefiles',  <----- This Line
                         '-DCMAKE_BUILD_TYPE={}'.format(build_type),
```


4. I compiled the project using the Mingw64 compiler, and fortunately, it worked perfectly fine.

By following these steps and utilizing the Mingw64 compiler, I was able to overcome the problem.

[MulticoreTSNE-0.1-cp37-cp37m-win_amd64.zip](https://github.com/DmitryUlyanov/Multicore-TSNE/files/11892662/MulticoreTSNE-0.1-cp37-cp37m-win_amd64.zip)
