### ISSUE TITLE
Failed building wheel for MulticoreTSNE

### ISSUE THREAD

**Issue by jasonz-dot** [DmitryUlyanov/Multicore-TSNE#77]
Hello,

I'm trying to install the MulticoreTSNE using the `pip install MulticoreTSNE`, but getting the following error:
```
/Users/jason/opt/miniconda3/lib/python3.8/site-packages/cmake/data/CMake.app/Contents/bin/cmake -E cmake_progress_start /private/var/folders/st/t3rpc2cn5m3c761j79yj7dm40000gn/T/pip-req-build-y8q7m_a5/build/temp.macosx-10.9-x86_64-3.8/CMakeFiles 0
  installing to build/bdist.macosx-10.9-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.macosx-10.9-x86_64
  creating build/bdist.macosx-10.9-x86_64/wheel
  creating build/bdist.macosx-10.9-x86_64/wheel/MulticoreTSNE
  copying build/lib.macosx-10.9-x86_64-3.8/MulticoreTSNE/libtsne_multicore.so -> build/bdist.macosx-10.9-x86_64/wheel/MulticoreTSNE
  creating build/bdist.macosx-10.9-x86_64/wheel/MulticoreTSNE/tests
  copying build/lib.macosx-10.9-x86_64-3.8/MulticoreTSNE/tests/__init__.py -> build/bdist.macosx-10.9-x86_64/wheel/MulticoreTSNE/tests
  copying build/lib.macosx-10.9-x86_64-3.8/MulticoreTSNE/tests/test_base.py -> build/bdist.macosx-10.9-x86_64/wheel/MulticoreTSNE/tests
  copying build/lib.macosx-10.9-x86_64-3.8/MulticoreTSNE/__init__.py -> build/bdist.macosx-10.9-x86_64/wheel/MulticoreTSNE
  running install_egg_info
  Copying MulticoreTSNE.egg-info to build/bdist.macosx-10.9-x86_64/wheel/MulticoreTSNE-0.1-py3.8.egg-info
  running install_scripts
  [WARNING] This wheel needs a higher macOS version than the version your Python interpreter is compiled against.  To silence this warning, set MACOSX_DEPLOYMENT_TARGET to at least 11_0 or recreate these files with lower MACOSX_DEPLOYMENT_TARGET:
  build/bdist.macosx-10.9-x86_64/wheel/MulticoreTSNE/libtsne_multicore.soTraceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/st/t3rpc2cn5m3c761j79yj7dm40000gn/T/pip-req-build-y8q7m_a5/setup.py", line 74, in <module>
      setup(
    File "/Users/jason/opt/miniconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Users/jason/opt/miniconda3/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/jason/opt/miniconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Users/jason/opt/miniconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/jason/opt/miniconda3/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 328, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/Users/jason/opt/miniconda3/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
      assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
  AssertionError: would build wheel with unsupported tag ('cp38', 'cp38', 'macosx_11_0_x86_64')
  ----------------------------------------
  ERROR: Failed building wheel for MulticoreTSNE
```
The version of python is 3.8.5, and the operating system is macOS Big Sur.
Any suggestions would be appreciated.

**Comment by jasonz-dot** [comment]
The problem disappeared when I installed the MulticoreTSNE in global. Maybe something not correctly configured with my conda environment.
